import time
import sys

from api.change_password import change_master_password
from api.create_vault import create_valut
from api.get_vaults import get_vaults
from api.retrieve_vault import retrieve_vault, retrieve_vault_id
from api.create_entry import create_entry
from api.get_entries import get_entries
from api.decrypt_entry import decrypt_entry

from cli.utils import get_number
from cli.home import home


def user_interface(username, master_password):
    print("********************SELECT AN OPTION***************")
    print("1. Change password")
    print("2. Create vault")
    print("3. View vaults")
    print("4. Select a vault")
    print("5. Logout/Exit")
    user_input = get_number("Please enter your selection: ", [1, 2, 3, 4, 5, 6])

    if user_input == 1:
        new_password = str(input("Enter your new password: "))
        password_change_result = change_master_password(username, master_password, new_password)
        if password_change_result:
            print("Your password has been changed.")
            time.sleep(5)
            user_interface(username, new_password)
        else:
            print("An error occurred. Please try again")
            time.sleep(5)
            user_interface(username, master_password)

    elif user_input == 2:
        vault_name_input = str(input("Enter a name for your vault (e.g. GMail): "))
        vault_creation = create_valut(username, master_password, vault_name_input)

        if vault_creation:
            print("Your vault has been created successfully.")
            # go to the vault interface with the information
            # generated by the new vault just created
            vault_details = retrieve_vault(username, vault_name_input)
            vault_interface(username, master_password, vault_details)
        else:
            print("An error occurred during the creation of the vault. Please try again.")

    elif user_input == 3:
        vaults_response = get_vaults(username)
        # must also display the vaults that they have been given access to 
        if len(vaults_response) == 0:
            print("You currently do not have any vaults.")
            print("If you do have vaults. An error has occurred and")
            print("we could not access your vaults.")
            time.sleep(2)
            user_interface(username, master_password)
        else:
            vaults = {}
            for counter, element in enumerate(vaults_response):
                print(f"{counter + 1}. Vault Name: {element[1]}")
                vaults[counter + 1] = element
            
            user_select_vault = int(input("select an item: "))
            if user_select_vault in vaults:
                vault_interface(username, master_password, vaults[user_select_vault])
            else:
                print("invalid input.")
                time.sleep(5)
                user_interface(username, master_password)

            if user_select_vault in vaults:
                vault_interface(username, master_password, vaults[user_select_vault])
            else:
                print("invalid input.")
                time.sleep(5)
                user_interface(username, master_password)

    elif user_input == 4:
        vault_input = str(input("Enter the name of the vault you want to access: "))
        # remember if the user doesnt own the vault they still may have access to the vault
        # need to also check the access_granted table to ensure this    
        vault_details = retrieve_vault(username, vault_input)
        vault_interface(username, master_password, vault_details)

    elif user_input == 5:
        # delete user details from memory
        del username
        del master_password
        # send the user back to the home page
        home()
        

def vault_interface(username, master_password, vault_details):
    # the vault details will be a tuple in the form:
    # (
    # vault_id,
    # vault_name,
    # username,
    # encrypted_key {text},
    # created_at,
    # updated_at
    # )
    display_vault = {
        "vault_id": 0,
        "vault_name": 1,
        "created_at": 4,
        "updated_at": 5
    }
    print("********** VAULT DETAILS**********")
    for name, index in display_vault.items():
        print(f"{name}: {vault_details[index]}")
    
    print("**********select an option**********")
    print("1. view passwords")
    print("2. Create new password")
    print("3. Delete password")
    print("4. Logout")
    user_input = get_number("Please enter your selection: ", [1, 2, 3, 4])

    if user_input == 1:
        print(f"********** Vault  - {vault_details[1]} - Passwords: **********")

        get_all_entries = get_entries(vault_details[0])

        print(f"this should be the response from get entries: {get_all_entries}")

        if len(get_all_entries) == 0:
            print("You have no password entries in this vault.")
            time.sleep(5)
            vault_interface(username, master_password, vault_details)
        else:
            for index, password in enumerate(get_all_entries):
                print("********************")
                print(f"PASSWORD {index + 1}:")
                print(f"PASSWORD TYPE: {password[3]}")
                print(f"PASSWORD: {
                    decrypt_entry(
                        username,
                        master_password,
                        # this encrypted vault key is a string since it is coming straight from the database
                        vault_details[3],
                        password[4]
                    )
                    }")
                print("********************")
            
            time.sleep(20)


    elif user_input == 2:
        password_type_input = str(input("Enter the password type (e.g. authentication): "))
        password_input = str(input("Enter the password: "))
        # need to generate the vault key
        create_entry_result = create_entry(
            username,
            master_password,
            vault_details[0],
            vault_details[1],
            vault_details[3],
            password_type_input,
            password_input
        )
        if create_entry_result:
            print("Your password has been created successfully.")
            print("You will be taken back to the vault interface.")
            vault_interface(
                username,
                master_password,
                vault_details
            )
        else:
            print("an error occurred when creating the password entry. please try again")
            time.sleep(5)
            vault_interface(username, master_password, vault_details)
    elif user_input == 3:
        user_input = str(input("enter the name of the entry you would like to delete: "))
        user_entries = get_entries(vault_details[0])
        entries_name = [x[3]for x in user_entries]

        if user_input not in entries_name:
            print("This entry does not exist in this vault")
            time.sleep(5)
            vault_interface(username, master_password, vault_details)
        else:
            pass
            # create functionality for deleteing a vault based of its name
            # e.g. type column
    elif user_input == 4:
        del username
        del master_password
        del vault_details
        sys.exit()


