import time
import sys

from api.change_password import change_master_password
from api.create_vault import create_valut
from api.get_vaults import get_vaults
from api.retrieve_vault import retrieve_vault
from api.create_entry import create_entry
# need to add create entry functionality

from cli.utils import get_number


def user_interface(username, master_password):
    print("********************SELECT AN OPTION***************")
    print("1. Change password")
    print("2. Create vault")
    print("3. View vaults")
    print("4. Select a vault")
    print("5. View someone else's vault")
    print("6. Logout/Exit")
    user_input = get_number("Please enter your selection: ", [1, 2, 3, 4, 5])

    if user_input == 1:
        new_password = str(input("Enter your new password: "))
        password_change_result = change_master_password(username, master_password, new_password)
        if password_change_result:
            print("Your password has been changed.")
            time.sleep(5)
            user_interface(username, new_password)
        else:
            print("An error occurred. Please try again")
            time.sleep(5)
            user_interface(username, master_password)

    elif user_input == 2:
        vault_name_input = str(input("Enter a name for your vault (e.g. GMail): "))
        vault_creation = create_valut(username, master_password, vault_name_input)

        if vault_creation:
            print("Your vault has been created successfully.")
            # go to the vault interface with the information
            # generated by the new vault just created
            vault_details = retrieve_vault(username, vault_name_input)
            vault_interface(username, master_password, vault_details)
        else:
            print("An error occurred during the creation of the vault. Please try again.")

    elif user_input == 3:
        vaults_response = get_vaults(username)
        # must also display the vaults that they have been given access to 
        if len(vaults_response) == 0:
            print("You currently do not have any vaults.")
            print("If you do have vaults. An error has occurred and")
            print("we could not access your vaults.")
            time.sleep(2)
            user_interface(username, master_password)
        else:
<<<<<<< HEAD
            vaults = {}
            for counter, element in enumerate(vaults_response):
                print(f"{counter + 1}. Vault Name: {element[1]}")
                vaults[counter + 1] = element
            
            user_select_vault = int(input("select an item: "))
            if user_select_vault in vaults:
                vault_interface(username, master_password, vaults[user_select_vault])
            else:
                print("invalid input.")
                time.sleep(5)
                user_interface(username, master_password)


=======
            vault_object = {}
            for index, element in enumerate(vaults_response):
                print(f"{index + 1}. Vault Name: {element[0]}")
                vault_object[index + 1] = element
            
            user_vault_input = int(input("Please select a vault: "))
            if user_vault_input in vault_object:
                vault_interface(username, master_password, vault_object[user_vault_input])
            else:
                print("Invalid input.")
                time.sleep(5)
                user_interface(username, master_password)
>>>>>>> vault_functionality
    elif user_input == 4:
        vault_input = str(input("Enter the name of the vault you want to access: "))
        # remember if the user doesnt own the vault they still may have access to the vault
        # need to also check the access_granted table to ensure this    
        vault_details = retrieve_vault(username, vault_input)
        vault_interface(username, master_password, vault_details)
    elif user_input == 5:
        # delete user details from memory
        del username
        del master_password
        # send the user back to the home page
        sys.exit()
        

def vault_interface(username, master_passowrd, vault_details):
    display_vault = {
        "vault_id": 0,
        "vault_name": 1,
        "created_at": 4,
        "updated_at": 5
    }
    print("**********VAULT DETAILS**********")
    for name, index in display_vault.items():
        print(f"{name}: {vault_details[index]}")
    
    print("**********select an option**********")
    print("1. Create new password")
    print("2. Give access")
    print("3. Revoke access")
    print("4. Delete password")

    user_input = get_number("Please enter your selection: ", [1, 2, 3, 4, 5])
    if user_input == 1:
        pass
    elif user_input == 2:
        user_name_input = str(input("enter the username of the user you want to grant vault access to: "))
        # grant access functionality
    elif user_input == 3:
        pass
    # revoke access functionality
    else:
        # delete entry functionality
        pass

def select_vaults(username, master_password, vaults):
    # display the users vaults
    vault_name = str(input("Enter the name of the vault you would like to access: "))